#!/usr/bin/env python3
"""
x09_ShowcaseMap.py — Generate an SS14 map that displays ALL Aavikko
prototype IDs as spawned entities in a grid.

For entity prototypes: spawn directly with proto: <id>
For jobIcon/statusIcon: spawn a custom "ShowcaseIcon" entity (defined in
  a generated prototype file) that has the sprite set directly — no
  inheritance, no merge issues.

Map is saved to 00_Aavikko/01_Resources/Maps/aavikko_showcase.yml
Prototype is saved to 00_Aavikko/01_Resources/Prototypes/Maps/aavikko_showcase.yml
Custom icon entities saved to 00_Aavikko/01_Resources/Prototypes/Aavikko/showcase_icons.yml

Usage:
    python3 x09_ShowcaseMap.py
    python3 x09_ShowcaseMap.py --spacing 2.0
    python3 x09_ShowcaseMap.py --list-only
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

DEFAULT_SPACING = 1.0
DEFAULT_ITEMS_PER_ROW = 15
DEFAULT_START_X = 0.5
DEFAULT_START_Y = 0.5

SPRITE_TYPES = {'jobIcon', 'statusIcon'}


def parse_prototypes(yml_dirs):
    """Parse all .yml files, return list of (type, id, sprite_path, sprite_state, abstract)."""
    prototypes = []
    seen_ids = set()

    for yml_dir in yml_dirs:
        if not yml_dir.exists():
            continue
        for yml_file in sorted(yml_dir.rglob("*.yml")):
            if yml_file.name in ("manifest.yml", "attributions.yml"):
                continue
            try:
                content = yml_file.read_text(encoding="utf-8")
            except OSError:
                continue

            current_type = None
            current_id = None
            current_abstract = False
            current_sprite = None
            current_state = None

            for line in content.split('\n'):
                stripped = line.strip()
                if stripped.startswith('- type:'):
                    if current_id and current_id not in seen_ids:
                        if not current_abstract and not current_id.startswith('Base'):
                            prototypes.append((current_type, current_id,
                                             current_sprite, current_state))
                            seen_ids.add(current_id)
                    m = re.match(r'- type:\s*["\']?([^"\'\s#]+)', stripped)
                    current_type = m.group(1) if m else None
                    current_id = None
                    current_abstract = False
                    current_sprite = None
                    current_state = None
                elif stripped.startswith('id:') and current_type:
                    m = re.match(r'id:\s*["\']?([^"\'\s#]+)', stripped)
                    if m:
                        current_id = m.group(1)
                elif stripped.startswith('abstract:') and 'true' in stripped:
                    current_abstract = True
                elif stripped.startswith('sprite:') and current_type in SPRITE_TYPES:
                    m = re.match(r'sprite:\s*(.+)', stripped)
                    if m:
                        current_sprite = m.group(1).strip().rstrip('#').strip()
                elif stripped.startswith('state:') and current_type in SPRITE_TYPES:
                    m = re.match(r'state:\s*["\']?([^"\'\s#]+)', stripped)
                    if m:
                        current_state = m.group(1)

            if current_id and current_id not in seen_ids:
                if not current_abstract and not current_id.startswith('Base'):
                    prototypes.append((current_type, current_id,
                                     current_sprite, current_state))
                    seen_ids.add(current_id)

    return sorted(prototypes, key=lambda x: x[1])


def generate_icon_prototypes(icons):
    """Generate entity prototypes for each icon — each has Sprite set directly,
    no parent inheritance, so no merge issues."""
    lines = [
        "# Auto-generated by x09_ShowcaseMap.py",
        "# Each entity displays a jobIcon/statusIcon sprite directly.",
        "# No parent inheritance — sprite is set explicitly to avoid merge issues.",
        "",
    ]
    for proto_type, proto_id, sprite_path, sprite_state in icons:
        safe_id = f"ShowcaseIcon_{proto_id}"
        lines.append(f"- type: entity")
        lines.append(f"  id: {safe_id}")
        lines.append(f'  name: "{proto_id}"')
        lines.append(f"  components:")
        lines.append(f"  - type: Sprite")
        lines.append(f"    sprite: {sprite_path}")
        lines.append(f"    noRot: true")
        lines.append(f"    layers:")
        if sprite_state:
            lines.append(f"    - state: {sprite_state}")
        else:
            lines.append(f"    - state: default")
        lines.append("")

    return "\n".join(lines)


def generate_map_yaml(prototypes, icons, spacing=DEFAULT_SPACING,
                      items_per_row=DEFAULT_ITEMS_PER_ROW,
                      start_x=DEFAULT_START_X, start_y=DEFAULT_START_Y,
                      template_path=None):
    """Generate map YAML.

    Entity prototypes: spawn directly.
    Icon prototypes: spawn generated ShowcaseIcon_ entity.
    """
    if template_path and template_path.exists():
        template = template_path.read_text(encoding="utf-8")
    else:
        template = (
            "meta:\n  format: 6\n  postmapinit: false\n"
            "tilemap:\n  0: Space\nentities:\n"
            '- proto: ""\n  entities:\n  - uid: 1\n    components:\n'
            "    - type: MetaData\n    - type: Transform\n    - type: LoadedMap\n...\n"
        )

    uids = re.findall(r'uid: (\d+)', template)
    next_uid = max(int(u) for u in uids) + 1 if uids else 2

    # Build icon ID → entity ID mapping
    icon_map = {}
    for proto_type, proto_id, sprite_path, sprite_state in icons:
        icon_map[proto_id] = f"ShowcaseIcon_{proto_id}"

    entity_lines = []
    entity_count = 0  # Track actual entity count (not line count!)
    
    # First: entity prototypes (direct spawn)
    for proto_type, proto_id, _, _ in prototypes:
        if proto_type != 'entity':
            continue
        i = entity_count
        row = i // items_per_row
        col = i % items_per_row
        x = start_x + col * spacing
        y = start_y + row * spacing

        entity_lines.append(f'- proto: {proto_id}')
        entity_lines.append("  entities:")
        entity_lines.append(f"  - uid: {next_uid}")
        entity_lines.append("    components:")
        entity_lines.append("    - type: Transform")
        entity_lines.append(f"      pos: {x},{y}")
        entity_lines.append("      parent: 2")
        next_uid += 1
        entity_count += 1

    # Then: icon prototypes (spawn generated entity)
    for proto_type, proto_id, sprite_path, sprite_state in icons:
        i = entity_count
        row = i // items_per_row
        col = i % items_per_row
        x = start_x + col * spacing
        y = start_y + row * spacing

        safe_id = f"ShowcaseIcon_{proto_id}"
        entity_lines.append(f'- proto: {safe_id}')
        entity_lines.append("  entities:")
        entity_lines.append(f"  - uid: {next_uid}")
        entity_lines.append("    components:")
        entity_lines.append("    - type: Transform")
        entity_lines.append(f"      pos: {x},{y}")
        entity_lines.append("      parent: 2")
        next_uid += 1
        entity_count += 1

    entities_block = "\n".join(entity_lines)

    if "...\n" in template:
        result = template.replace("...\n", entities_block + "\n...\n")
    elif template.rstrip().endswith("..."):
        result = template.rstrip()[:-3] + entities_block + "\n...\n"
    else:
        result = template.rstrip() + "\n" + entities_block + "\n"

    result = result.replace("id: Empty", "id: AavikkoShowcase")
    result = result.replace('"Empty Debug Map"', '"Aavikko Showcase Map"')

    return result


def generate_map_prototype():
    return (
        "- type: gameMap\n"
        "  id: AavikkoShowcase\n"
        "  mapName: 'Aavikko Showcase'\n"
        "  mapPath: /Maps/aavikko_showcase.yml\n"
        "  minPlayers: 0\n"
        "  maxPlayers: 1\n"
        "  fallback: false\n"
        "  stations:\n"
        "    AavikkoShowcase:\n"
        "      stationProto: StandardNanotrasenStation\n"
        "      components:\n"
        "        - type: StationNameSetup\n"
        "          mapNameTemplate: 'Aavikko Showcase'\n"
        "        - type: StationJobs\n"
        "          availableJobs:\n"
        "            Passenger: [ -1, -1 ]\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Generate SS14 showcase map with all Aavikko prototypes"
    )
    parser.add_argument("--spacing", type=float, default=DEFAULT_SPACING)
    parser.add_argument("--per-row", type=int, default=DEFAULT_ITEMS_PER_ROW)
    parser.add_argument("--list-only", action="store_true")
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    build_root = script_dir.parent.parent.parent
    resources_dir = build_root / "00_Aavikko" / "01_Resources"

    patches_dir = resources_dir / "Patches"
    mods_dir = resources_dir / "Mods"

    prototypes = parse_prototypes([patches_dir, mods_dir])

    entities = [p for p in prototypes if p[0] == 'entity']
    icons = [p for p in prototypes if p[0] in SPRITE_TYPES and p[2]]
    skipped = [p for p in prototypes if p[0] != 'entity' and p[0] not in SPRITE_TYPES]

    print(f"Found {len(prototypes)} total prototypes:")
    print(f"  {len(entities)} entity (direct spawn)")
    print(f"  {len(icons)} jobIcon/statusIcon (custom entity)")
    print(f"  {len(skipped)} other (skipped)")

    if args.list_only:
        print("\nEntity prototypes:")
        for _, pid, _, _ in entities:
            print(f"  [entity] {pid}")
        print("\nSprite prototypes:")
        for ptype, pid, sprite, state in icons:
            print(f"  [{ptype}] {pid} → {sprite}:{state}")
        return 0

    # 1. Generate custom icon entity prototypes
    #    Saved to 00_Aavikko/01_Resources/Mods/Prototypes/Aavikko/showcase_icons.yml
    #    (in Mods/ so Apply.py copies them to Resources/)
    if icons:
        icon_proto_path = resources_dir / "Mods" / "Prototypes" / "Aavikko" / "showcase_icons.yml"
        icon_proto_path.parent.mkdir(parents=True, exist_ok=True)
        icon_proto_path.write_text(generate_icon_prototypes(icons), encoding="utf-8")
        print(f"\nIcon prototypes: {icon_proto_path} ({len(icons)} entities)")

    # 2. Generate map using empty.yml as template
    #    Map file saved to 00_Aavikko/01_Resources/Mods/Maps/aavikko_showcase.yml
    #    (in Mods/ so Apply.py copies it to Resources/Maps/)
    template = build_root / "Resources" / "Maps" / "Test" / "empty.yml"
    map_yaml = generate_map_yaml(
        prototypes, icons, spacing=args.spacing, items_per_row=args.per_row,
        template_path=template
    )

    spawnable = len(entities) + len(icons)
    map_path = resources_dir / "Mods" / "Maps" / "aavikko_showcase.yml"
    map_path.parent.mkdir(parents=True, exist_ok=True)
    map_path.write_text(map_yaml, encoding="utf-8")
    print(f"Map saved: {map_path}")
    print(f"  {spawnable} entities ({len(entities)} direct + {len(icons)} icon)")
    print(f"  Grid: {args.per_row}/row, {args.spacing} spacing")

    # 3. gameMap prototype — also in Mods/
    proto_path = resources_dir / "Mods" / "Prototypes" / "Maps" / "aavikko_showcase.yml"
    proto_path.parent.mkdir(parents=True, exist_ok=True)
    proto_path.write_text(generate_map_prototype(), encoding="utf-8")
    print(f"  Prototype: {proto_path}")

    print(f"\nTo load: forcemap AavikkoShowcase")
    print(f"To freeze: togglesubscriber")
    return 0


if __name__ == "__main__":
    sys.exit(main())
